### PR TITLE
GUILD-574: Fix KafkaSource crashing on imports when import hooks are …

### LINKED ISSUE #73: KafkaSource crashes on bulk-import if import hooks are disabled
If you have a KafkaSource with import hooks disabled:

```ruby
  def self.kafka_config
    {
      update: true,
      delete: true,
      import: false,
      create: true
    }
  end
```

Doing a bulk import that only updates (no inserts) on that class will fail with the following error:

```
NoMethodError: undefined method `num_inserts' for nil:NilClass
```

This seems to be because the early return in the `import_without_validations_or_callbacks` monkey patch does not return the `results` from `super`

```
        results = super
        return unless self.kafka_config[:import] #### Here
        return if array_of_attributes.empty? #### And here
```

The activerecord-import gem later tries to use the results of the monkey patched method like this and crashes (because it's nil). See import.rb:735

```
      return_obj.num_inserts = 0 if return_obj.num_inserts.nil?
```

### PR DESCRIPTION
**Pull request by DeeChau**
…disabled

# Pull Request Template

## Description

Return `ActiveRecord::Import::Result.new([], 0, [], [])` when the kafka_config `import` is not set or the result set is empty.
Fixes an issue where KafkaSource crashes on bulk-imports if import hooks are disabled.

Fixes #73

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Unit Tests

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: lib/deimos/kafka_source.rb [hunk 1]
```diff
@@ -88,8 +88,9 @@ def import_without_validations_or_callbacks(column_names,
                                                   array_of_attributes,
                                                   options={})
         results = super
-        return unless self.kafka_config[:import]
-        return if array_of_attributes.empty?
+        if !self.kafka_config[:import] || array_of_attributes.empty?
+          return ActiveRecord::Import::Result.new([], 0, [], [])
+        end
```
Comment (dorner) [inline lib/deimos/kafka_source.rb:93]: Is there a reason you can't just return `results` here?

**Review by dorner — CHANGES_REQUESTED** [review]

File: lib/deimos/kafka_source.rb (hunk 1 above)
Comment (DeeChau) [reply lib/deimos/kafka_source.rb:93]: oh good point, will try that out - i forgot that we called `super` haha

Comment (DeeChau) [reply lib/deimos/kafka_source.rb:93]: Yeah - the `results` from `super` works with this too

**Review by dorner — APPROVED** [review]
