### PR TITLE
#195 Fix buffer overflow exception handling

### LINKED ISSUE #195: NoMethodError: undefined method `decoder'
When db_producer catches `Kafka::MessageSizeTooLarge` exception then  [log attempt ](https://github.com/flipp-oss/deimos/blob/master/lib/deimos/utils/db_producer.rb#L103) fails  with "NoMethodError: undefined method "decoder'" exception while trying to decode message for logging with `Deimos::KafkaMessage.decoded(messages)`

backtrace:
```
deimos-ruby-1.22.3/lib/deimos/kafka_message.rb:46:in `block in decoded'",
activerecord-6.1.7.4/lib/active_record/relation/delegation.rb:88:in `each'",
activerecord-6.1.7.4/lib/active_record/relation/delegation.rb:88:in `each'",
deimos-ruby-1.22.3/lib/deimos/kafka_message.rb:43:in `map'",
deimos-ruby-1.22.3/lib/deimos/kafka_message.rb:43:in `decoded'",
deimos-ruby-1.22.3/lib/deimos/utils/db_producer.rb:103:in `rescue in block in process_topic_batch'",
```

looks like Deimos::KafkaMessage.decoded messed up with `.new` call
a possible solution could be `.decoded` method updated as:
```
    def self.decoded(messages=[])
      return [] if messages.empty?

      decoder_class = self.decoder(messages.first.topic)
      decoder = decoder_class&.new
      messages.map do |m|
        {
          key: m.key.present? ? decoder&.decode_key(m.key) || m.key : nil,
          payload: decoder_class&.decoder&.decode(m.message) || m.message
        }
      end
    end
```

### PR DESCRIPTION
**Pull request by 2rba**
## Description
`@logger.error(Deimos::KafkaMessage.decoded(messages))` in the rescue block fails to decode the message and causes wrong exception raised
This PR:
- fixes message decoding
- adds rescue block around decoding call to make sure if decode is misconfigured that does not interfere with original exception

Fixes #195

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
tests added

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added a line in the CHANGELOG describing this change, under the UNRELEASED heading
- [ ] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: spec/utils/db_producer_spec.rb [hunk 1]
```diff
@@ -308,35 +309,6 @@
       Deimos.unsubscribe(subscriber)
     end
 
-    it 'should delete messages on buffer overflow' do
```
Comment (2rba) [inline spec/utils/db_producer_spec.rb:311]: moved to the context block above

**Review by dorner — APPROVED** [review]

**Comment by dorner** [comment]
Thanks so much for the contribution!
