### PR TITLE
GH-50: Raise error if no topic is given while producing messages

### LINKED ISSUE #50: Fail explicitly when no topic given
Currently, if a producer is configured to have a blank topic (e.g. an environment variable that has no value), Deimos doesn't error out until it actually tries to produce to the topic. RubyKafka also doesn't error out, it just says "can't assign partitions". This is super confusing. Deimos should fail immediately when it tries to produce and no topic is configured.

cc: @kentkhlui

### PR DESCRIPTION
**Pull request by angad-singh**
# Pull Request Template

## Description

Changed the `publish_list` method in `lib/deimos/producer.rb` to raise error if the topic is blank.

Fixes #50 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Unit Tests
- [x] Using the `ItemAttributeChangeProducer` in Fadmin

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: lib/deimos/producer.rb [hunk 1]
```diff
@@ -104,6 +104,8 @@ def publish_list(payloads, sync: nil, force_send: false, topic: self.topic)
                   Deimos.config.producers.disabled ||
                   Deimos.producers_disabled?(self)
 
+        raise 'Topic not given! Please specify the topic.' if topic.blank?
```
Comment (dorner) [inline lib/deimos/producer.rb:107]: Can we change the wording to "Topic not specified"?

File: spec/producer_spec.rb [hunk 2]
```diff
@@ -296,6 +296,16 @@ def self.partition_key(payload)
...
 
+    it 'should error if no topic is given' do
+      expect { MyProducer.publish_list(
+          [{ 'test_id' => 'foo', 'some_int' => 123 },
+           { 'test_id' => 'bar', 'some_int' => 124 }],
+          topic: ""
+      ) }.to raise_error(RuntimeError,
+                             'Topic not given! Please specify the topic.')
+
+    end
```
Comment (dorner) [inline spec/producer_spec.rb:307]: Should also test the case where you create a producer with no topic configured and don't pass any topic in explicitly.

**Review by dorner — CHANGES_REQUESTED** [review]

File: spec/producer_spec.rb (hunk 2 above)
Comment (angad-singh) [reply spec/producer_spec.rb:315]: Added. @dorner

Comment (angad-singh) [reply spec/producer_spec.rb:315]: oh I forgot to fix the linter issues, gonna do that after my meeting

**Review by dorner — DISMISSED** [review]

**Comment by dorner** [comment]
@angad-singh please fix Rubocop errors and then we're good to merge!

**Review by angad-singh — COMMENTED** [review]
@dorner the Rubocop issues have been resolved :)

**Review by dorner — APPROVED** [review]

**Comment by dorner** [comment]
Woot, thanks!
